steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build ONNX container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/mlops_onnx_image',
    '-f',
    'dockerfiles/onnx_api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push ONNX container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/mlops_onnx_image'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy ONNX API to Cloud Run'
  args: [
    'run',
    'deploy',
    'mlops-onnx-api',
    '--image',
    'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/mlops_onnx_image',
    '--region',
    'europe-west1',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
