steps:
  # Step 1: Build the Docker image for the frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/frontend:latest', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/frontend:latest']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/frontend:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/premium-portal-447810-a6/group5-repo/frontend:latest'
