program: src/mlops_grp5/train.py
name: sweepdemo
project: mlops-grp5
#entity: mlops-grp5 
method: grid
metric:
    goal: minimize
    name: validation_loss
parameters:
    learning-rate:
        values: [0.001, 0.01, 0.1]
    max-epochs:
        values: [5, 10, 15]
    weight-decay:
        values: [0.001, 0.01, 0.1]